# Generated by Django 4.2.2 on 2023-06-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
                ('meaning', models.CharField(max_length=300)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='main_app.character')),
            ],
        ),
    ]
